export const Strings = {
  'str NaN': 'NaN',
  'str null': 'null',
  'str undefined': 'undefined',
  'str true': 'true',
  'str false': 'false',
  'str 0': '0',
  'str -1': '-1',
  'str -1.5': '-1.5',
  'str 0.42': '0.42',
  'str .42': '.42',
  'str 1.2E+9': '1.2E+9',
  'str 0xFF': '0xFF',
  'str Inf..': 'Infinity',
  'str empty': '',
  'str space': ' ',
  'str [Ob]': '[object Object]',
  'str dot': '.',
  'str +': '+',
  'str -': '-',
  'str 99,999': '99,999',
  'str date': '2077-06-04',
  'str #abcdef': '#abcdef',
  'str 1.2.3': '1.2.3',
  'str blah': 'blah',
}
