// from x => typeof x
export const NUL = 'null'
export const UND = 'undefined'
export const BOO = 'boolean'
export const NUM = 'number'
export const BIG = 'bigint'
export const STR = 'string'
export const OBJ = 'object'
export const FUN = 'function'
export const SYM = 'symbol'

export const NUMSTR = 'numstr'
export const MISC = 'misc'
export const FLOAT = 'float'
export const INT = 'int'
export const RATIO = 'ratio'
